# Generated by Django 3.2.9 on 2021-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
                ('pokedex', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Pokemony',
            },
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
