# Generated by Django 3.2.9 on 2021-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20211106_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Typ',
            },
        ),
        migrations.AlterField(
            model_name='pokemony',
            name='pokedex',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
