# Generated by Django 3.2.9 on 2021-11-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_auto_20211106_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemony',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Items.typ'),
        ),
        migrations.AlterField(
            model_name='pokemony',
            name='pokedex',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
