# Generated by Django 3.2.9 on 2021-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20211106_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasyfikacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Klasyfikacja',
            },
        ),
    ]
