# Generated by Django 3.2.9 on 2021-11-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_klasyfikacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemony',
            name='klasyfikacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Items.klasyfikacja'),
        ),
    ]
